name: Release Workflow

on:
  release:
    types:
      - created

concurrency:
  group: release_workflow
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_ipa:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat .github/workflows/versions.env >> $GITHUB_ENV
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Prepare IOS Release Build
        env:
          FLUFFYCHAT_INSTALL_IPA: 0
          FLUFFYCHAT_NEW_TEAM: 'none'
          FLUFFYCHAT_NEW_GROUP: 'uwu.vivy.fluffychat'
        run: ./scripts/release-ios-testflight.sh
      - name: Create zip
        run: zip -r fluffychat.zip build/ios/iphoneos/Runner.app
      - name: Archive .zip file
        uses: actions/upload-artifact@v3
        with:
          name: fluffychat.zip
          path: fluffychat.zip
